### ISSUE TITLE
Change name -> authorName

### ISSUE THREAD

**Issue by acabunoc** [mozillascience/PaperBadger#101]
To avoid confusion with badge.name vs. badgeInstance.name

https://github.com/mozillascience/PaperBadger/issues/86#issuecomment-134657843

Flag @Alicole when live

**Comment by acabunoc** [comment]
@Alicole - it's done here: https://github.com/acabunoc/badgekit-api/commit/d67bcdfefa7aca352878ad080a019f6b8e648575

**Comment by Alicole** [comment]
@acabunoc -- that's helpful thank you :+1 

Will be much easier to target and separate out the author name in future, from each JSON object.

Also make help to make the code more bullet proof too.

Have now incorporated AuthorName change into source code.

You will need to change all references from "name" to "authorName", so that the visuals display correctly.

**Comment by acabunoc** [comment]
@Alicole - ah, yes please! commit away. I'll merge afterwards :)

**Comment by Alicole** [comment]
@acabunoc Will I need a new pull request?

**Comment by acabunoc** [comment]
@Alicole - nope! If you push to the same branch it will update the pull request
